######################################################################
# Automatically generated by qmake (3.0) Sat Apr 22 06:43:01 2017
######################################################################

TEMPLATE = app
TARGET = birthdays
INCLUDEPATH += .

# Input
SOURCES += main.cpp
