######################################################################
# Automatically generated by qmake (3.0) Mon Apr 24 00:26:16 2017
######################################################################

TEMPLATE = app
TARGET = birthdays
INCLUDEPATH += .

# Input
HEADERS += person.h
SOURCES += main.cpp person.cpp
